# Generated by Django 5.2.7 on 2026-01-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_pui', models.CharField(help_text='Public Program Unique Identifier', max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('ops_nom', models.CharField(help_text='Operations Nomenclature', max_length=100)),
                ('eng_nom', models.CharField(help_text='Engineering Nomenclature', max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
