# Generated by Django 5.2.7 on 2026-01-05 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('public_pui', models.CharField(help_text='Public Program Unique Identifier', max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('ops_nom', models.CharField(help_text='Operations Nomenclature', max_length=100)),
                ('eng_nom', models.CharField(help_text='Engineering Nomenclature', max_length=100)),
                ('unit', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('calibrated_data', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('status_class', models.CharField(blank=True, max_length=50, null=True)),
                ('status_indicator', models.CharField(blank=True, max_length=50, null=True)),
                ('status_color', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry_storage.telemetrychannel')),
            ],
            options={
                'indexes': [models.Index(fields=['channel', '-timestamp'], name='telemetry_s_channel_00c775_idx'), models.Index(fields=['created_at', 'timestamp'], name='telemetry_s_created_6faed6_idx')],
                'constraints': [models.UniqueConstraint(fields=('id', 'timestamp'), name='unique_id_timestamp')],
            },
        ),
    ]
