# Generated by Django 5.2.7 on 2026-01-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_storage', '0002_timescaledb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetryreading',
            name='deleted_at',
        ),
    ]
