# Generated by Django 5.2.7 on 2026-02-18 12:45

from django.db import migrations, models

# Delete duplicate (channel_id, timestamp) rows, keeping the first-written
# (smallest UUIDv7 id) for each pair. Runs before the unique constraint is
# added so the constraint creation cannot fail on pre-existing duplicates.
#
# TimescaleDB decompresses rows on-the-fly for DML against compressed chunks.
# The default limit (100 000 tuples) is too low for this bulk delete, so we
# raise it to 0 (unlimited) for the session before the DELETE runs. The SET is
# session-scoped and resets automatically when the connection is returned.
DEDUP_SQL = """
SET timescaledb.max_tuples_decompressed_per_dml_transaction = 0;
DELETE FROM telemetry_storage_telemetryreading
WHERE id NOT IN (
    SELECT DISTINCT ON (channel_id, timestamp) id
    FROM telemetry_storage_telemetryreading
    ORDER BY channel_id, timestamp, id
);
"""


class Migration(migrations.Migration):
    dependencies = [
        ("telemetry_storage", "0003_remove_telemetryreading_deleted_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="telemetryreading",
            name="unique_id_timestamp",
        ),
        migrations.RunSQL(
            sql=DEDUP_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="telemetryreading",
            constraint=models.UniqueConstraint(
                fields=("channel", "timestamp"), name="unique_channel_timestamp"
            ),
        ),
    ]
