# Generated by Django 5.2.7 on 2026-01-30 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('processor_name', models.CharField(help_text='Unique processor identifier', max_length=100, unique=True)),
                ('last_processed_at', models.DateTimeField(blank=True, help_text='Last successfully analyzed data timestamp', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Last execution start time', null=True)),
                ('state_data', models.JSONField(blank=True, help_text='Processor-specific state data', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectedEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text="Event category (e.g., 'urination', 'temp_spike')", max_length=50)),
                ('channel_id', models.CharField(help_text="PUI of source channel (e.g., 'NODE3000004')", max_length=50)),
                ('detected_at', models.DateTimeField(help_text='Logical timestamp of event occurrence')),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Detection confidence (0.00–1.00)', max_digits=3)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Processor-specific detection details (trend data, thresholds, etc.)')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', '-detected_at'], name='event_proce_event_t_b27721_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(help_text="Social platform (e.g., 'twitter', 'mastodon')", max_length=50)),
                ('external_id', models.CharField(help_text='Platform-specific post ID (e.g., tweet ID)', max_length=100)),
                ('content', models.TextField(help_text='The posted text content')),
                ('posted_at', models.DateTimeField(help_text='When the post was published')),
                ('event', models.ForeignKey(help_text='Reference to the triggering DetectedEvent', on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='event_processors.detectedevent')),
            ],
            options={
                'indexes': [models.Index(fields=['platform', '-posted_at'], name='event_proce_platfor_3ed99b_idx')],
            },
        ),
    ]
