# Generated by Django 5.2.7 on 2026-02-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_processors', '0001_create_event_processor_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message if post failed'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='Post status: pending, success, or failed', max_length=20),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='external_id',
            field=models.CharField(blank=True, default='', help_text='Platform-specific post ID (e.g., tweet ID). Empty if failed.', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='When the post was published. Null if failed.', null=True),
        ),
        migrations.AddIndex(
            model_name='socialpost',
            index=models.Index(fields=['platform', 'status'], name='event_proce_platfor_0de0c8_idx'),
        ),
    ]
