# Generated by Django 5.2.7 on 2026-02-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_processors', '0002_add_socialpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedevent',
            name='confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Detection confidence (0.00-1.00)', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='external_id',
            field=models.CharField(blank=True, default='', help_text='Platform-specific post ID (e.g., Bluesky post URI). Empty if failed.', max_length=100),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(help_text="Social platform (e.g., 'bluesky')", max_length=50),
        ),
    ]
