# Generated by Django 5.2.7 on 2026-02-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_processors', '0003_alter_detectedevent_confidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processorstate',
            old_name='last_processed_at',
            new_name='last_processed_timestamp',
        ),
    ]
