"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
from pathlib import Path
from typing import Any, cast

import environ
import sentry_sdk
from django.db import OperationalError
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.types import Event

# Initialize django-environ
env = environ.Env(
    # Set default values and casting
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# base.py is in config/settings/, so we need to go up 3 levels to reach project root
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Read .env file
dotenv_path = os.environ.get("DOTENV_PATH")
if dotenv_path:
    # If custom env file is specified, it should override any pre-loaded
    # environment variables (e.g. from IDE or runner defaults)
    env_file = BASE_DIR / dotenv_path
    environ.Env.read_env(env_file, overwrite=True)
else:
    env_file = BASE_DIR / ".env"
    environ.Env.read_env(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "drf_spectacular",
    # Project apps
    "apps.core",
    "apps.telemetry_storage",
    "apps.telemetry_ingestion",
    "apps.event_processors",
    "apps.dashboards",
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "PeeBot API",
    "DESCRIPTION": "Read-only telemetry and event APIs with manual debug injection.",
    "VERSION": "1.0.0",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

TOTAL_POOL_SIZE = 20

DATABASES = {"default": env.db()}

# Database connection pooling
DATABASES["default"]["CONN_MAX_AGE"] = 0
DATABASES["default"]["CONN_HEALTH_CHECKS"] = True


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation"
        ".UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ==============================================================================
# Celery Configuration
# ==============================================================================

# Celery broker and result backend configuration
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://localhost:6379/0")

# Task serialization
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Timezone configuration
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Task result configuration
CELERY_RESULT_EXTENDED = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit

# Celery Beat uses the default PersistentScheduler (file-based).
# Schedule is defined statically in config/celery.py via app.conf.beat_schedule.
# See ADR-009 in docs/system-solution/tech-decisions.md for rationale.

# ==============================================================================
# External API Configuration
# ==============================================================================

# OpenRouter / LLM Configuration
OPENROUTER_API_KEY = env("OPENROUTER_API_KEY", default=None)
OPENROUTER_BASE_URL = env("OPENROUTER_BASE_URL", default="https://openrouter.ai/api/v1")
OPENROUTER_MODEL = env("OPENROUTER_MODEL", default="deepseek/deepseek-chat")
JOKE_GENERATOR_MAX_RETRIES = env.int("JOKE_GENERATOR_MAX_RETRIES", default=3)
JOKE_GENERATOR_BASE_DELAY = env.float("JOKE_GENERATOR_BASE_DELAY", default=1.0)

# Bluesky API Configuration
BLUESKY_HANDLE = env("BLUESKY_HANDLE", default=None)
BLUESKY_APP_PASSWORD = env("BLUESKY_APP_PASSWORD", default=None)
BLUESKY_COOLDOWN_MINUTES = env.int("BLUESKY_COOLDOWN_MINUTES", default=30)

# Social Dry-Run Mode
# When True, the event detection pipeline runs as normal BUT joke generation
# and any external posting (e.g. to Bluesky or other social platforms) are
# skipped. A SocialPost record is still created (status=SUCCESS,
# external_id="dry-run://mock") for observability. Set to True in
# preview/staging environments.
SOCIAL_DRY_RUN = env.bool("SOCIAL_DRY_RUN", default=False)

# ==============================================================================
# Sentry Configuration
# ==============================================================================

SENTRY_DSN = env("SENTRY_DSN", default=None)
SENTRY_ENVIRONMENT = env("SENTRY_ENVIRONMENT", default="development")

SENTRY_LOGS_LEVEL = env("SENTRY_LOGS_LEVEL", default="INFO")

_VALID_LOG_LEVELS = {"DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"}
if SENTRY_LOGS_LEVEL not in _VALID_LOG_LEVELS:
    raise ValueError(
        f"SENTRY_LOGS_LEVEL must be one of {sorted(_VALID_LOG_LEVELS)}, "
        f"got: {SENTRY_LOGS_LEVEL!r}"
    )


def _sentry_before_send(event: Event, hint: dict[str, Any]) -> Event | None:
    request = event.get("request")
    if isinstance(request, dict):
        url = request.get("url", "")
        if isinstance(url, str) and (url.endswith("/healthz") or url.endswith("/readyz")):
            return None

    # Suppress transient DB connection errors that originate from a Celery task.
    # The task already retries on OperationalError (autoretry_for + max_retries=3),
    # so intermediate captures are noise. A genuine prolonged outage will still
    # surface through health checks and logging once all retries are exhausted.
    exc_info = hint.get("exc_info")
    if exc_info is not None and isinstance(exc_info[1], OperationalError):
        exception = event.get("exception")
        values: list[Any] = (
            exception.get("values", []) if isinstance(exception, dict) else []
        )
        last_value = values[-1] if values else None
        mechanism = (
            last_value.get("mechanism", {}) if isinstance(last_value, dict) else {}
        )
        if isinstance(mechanism, dict) and mechanism.get("type") == "celery":
            return None

    return event


if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=SENTRY_ENVIRONMENT,
        integrations=[
            DjangoIntegration(),
            # Controls breadcrumb capture (level) and automatic issue creation
            # (event_level) from Python log records — separate from Sentry Logs.
            LoggingIntegration(
                level=logging.INFO,  # Capture INFO+ as breadcrumbs
                event_level=logging.ERROR,  # Send ERROR+ as Sentry issues
                sentry_logs_level=getattr(logging, SENTRY_LOGS_LEVEL),
            ),
            # Instruments Celery tasks as Sentry spans and enables Sentry Crons
            # check-in monitoring for Celery Beat periodic tasks.
            CeleryIntegration(monitor_beat_tasks=True),
        ],
        # Capture 100% of transactions in development; tune down in production.
        traces_sample_rate=env.float("SENTRY_TRACES_SAMPLE_RATE", default=1.0),
        send_default_pii=False,
        # Enable Sentry Logs — forwards Python log records to Sentry's Logs UI.
        enable_logs=True,
        before_send=cast(Any, _sentry_before_send),
    )
